package blueprint

type FirstbootCustomization struct {
	CommonCustomization

	CustomFirstbootCustomization
	SatelliteFirstbootCustomization
	AAPFirstbootCustomization
}

// CommonCustomization contains common fields for all firstboot customizations.
type CommonCustomization struct {
	// Type of the firstboot customization. Supported values are:
	// "custom", "satellite", and "aap".
	Type string `json:"type,omitempty" toml:"type,omitempty"`

	// Optional firstboot name. Must be unique within the blueprint and only
	// alphanumeric characters with dashes and underscores are allowed.
	Name string `json:"name,omitempty" toml:"name,omitempty"`

	// Ignore errors when executing the firstboot script and continue with
	// execution of the following firstboot scripts, if any. By default,
	// firstboot scripts are executed in order and if one of them fails, the
	// execution stops immediately.
	IgnoreFailure bool `json:"ignore_failure,omitempty" toml:"ignore_failure,omitempty"`
}

// CustomFirstbootCustomization contains fields specific to custom firstboot
// customizations. All fields must be prefixed with "Custom".
type CustomFirstbootCustomization struct {
	// Strings without shebang will be interpreted as shell scripts, otherwise
	// the script will be executed using the shebang interpreter. Required if
	// type is set to "custom".
	CustomContents string `json:"custom_contents,omitempty" toml:"custom_contents,omitempty"`
}

// SatelliteFirstbootCustomization contains fields specific to satellite firstboot
// customizations. All fields must be prefixed with "Satellite".
type SatelliteFirstbootCustomization struct {
	// Optional CA certificate to enroll into the system before executing the
	// firstboot script.
	SatelliteCACerts []string `json:"satellite_cacerts,omitempty" toml:"satellite_cacerts,omitempty"`

	// Registration command as generated by the Satellite server. Required, if
	// type is set to "satellite".
	SatelliteCommand string `json:"satellite_command,omitempty" toml:"satellite_command,omitempty"`
}

// AAPFirstbootCustomization contains fields specific to AAP firstboot
// customizations. All fields must be prefixed with "AAP".
type AAPFirstbootCustomization struct {
	// Optional CA certificate to enroll into the system before executing the
	// firstboot script.
	AAPCACerts []string `json:"aap_cacerts,omitempty" toml:"aap_cacerts,omitempty"`

	// Job template URL as generated by the AAP server. Required if type is set
	// to "aap". Example URLs are
	// https://aap.example.com/api/controller/v2/job_templates/9/callback/ or
	// https://aap.example.com/api/v2/job_templates/9/callback/ depending on the
	// AAP version.
	AAPJobTemplateURL string `json:"aap_job_template_url,omitempty" toml:"aap_job_template_url,omitempty"`

	// The host config key. Required if type is set to "aap".
	AAPHostConfigKey string `json:"aap_host_config_key,omitempty" toml:"aap_host_config_key,omitempty"`
}
