name: Tests

"on":
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: "🛃 Unit tests"
    runs-on: ubuntu-22.04
    container:
      image: registry.fedoraproject.org/fedora:41

    steps:
      - name: Install build and test dependencies
        run: dnf -y install git-core go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Mark the working directory as safe for git
        run: git config --global --add safe.directory "$(pwd)"

      - name: Run unit tests
        run: go test ./...

  golang-lint:
    name: "⌨ Golang Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.64"
          skip-cache: true
          args: --verbose --timeout 5m0s

  tagseq:
    name: "Struct tags conistency check"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run go struct consistency checker
        run: go run github.com/mvo5/vet-tagseq/cmd/tagseq@latest ./...
